let autos = [
    {
        marca:"Ford",
        modelo:"Fiesta",
        color:"Azul",
        anio:2019,
        km:200,
        precio:150000,
        cuotas:12,
        patente:"APL123",
        vendido:true,
    },
     {
        marca:"Toyota",
        modelo:"Corolla",
        color:"Blanco",
        anio:2019,
        km:0,
        precio:100000,
        cuotas:14,
        patente:"JJK116",
        vendido:false,
    },
    {
        marca:"Suzuki",
        modelo:"Fun",
        color:"Rojo",
        anio:2010,
        km:120.000,
        precio:50000,
        cuotas:14,
        patente:"HZH882",
        vendido:true,
    }
]
module.exports = autos;